# Generated by Django 4.2.5 on 2023-09-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendstatistic',
            name='clicks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spendstatistic',
            name='conversion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spendstatistic',
            name='impressions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
